# Generated by Django 5.2.17 on 2026-10-05 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_insurer_review_approval_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='inference_provider',
            field=models.CharField(blank=True, help_text='Hugging Face routing provider or policy (e.g. auto, fastest, cheapest, preferred). Leave blank for automatic routing.', max_length=80),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Lower numbers are selected first. Multiple text and vision providers may be active.'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='secret_reference',
            field=models.CharField(blank=True, help_text='Environment variable containing the API token; takes precedence over API key.', max_length=160),
        ),
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='provider',
            field=models.CharField(choices=[('OLLAMA', 'Ollama / Llama'), ('HUGGINGFACE', 'Hugging Face Inference Providers / Endpoint'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic Claude'), ('OPENAI_COMPATIBLE', 'OpenAI-compatible API')], max_length=30),
        ),
        migrations.CreateModel(
            name='EmailAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(blank=True, help_text='An exact sender address. Alternatively select a portal user or authorized group.', max_length=254)),
                ('permitted_types', models.JSONField(blank=True, default=list, help_text='Allowed types: ["ADDITION", "DELETION"]. Empty permits both.')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, help_text='Active portal members of this group may submit replies for this policy.', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_authorities', to='core.policy')),
                ('processing_user', models.ForeignKey(blank=True, help_text='Required for external email addresses without a matching portal user. Used for workflow attribution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_email_authorities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_authorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('message_uid', models.CharField(max_length=512)),
                ('message_id', models.CharField(blank=True, max_length=512)),
                ('in_reply_to', models.CharField(blank=True, max_length=512)),
                ('references_header', models.TextField(blank=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=998)),
                ('body_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('raw_message', models.FileField(blank=True, upload_to='inbound/%Y/%m/')),
                ('processing_state', models.CharField(choices=[('RECEIVED', 'Received'), ('NEEDS_INFO', 'Awaiting correction'), ('PROCESSED', 'Processed'), ('UNAUTHORIZED', 'Unauthorized sender'), ('NEEDS_REVIEW', 'Needs review'), ('IGNORED', 'Ignored automatic reply')], default='RECEIVED', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailauthority')),
                ('endorsement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_emails', to='core.endorsementrequest')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.policy')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.inboundemail')),
            ],
            options={
                'ordering': ('-received_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=998)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField()),
                ('correction_csv', models.TextField(blank=True)),
                ('message_id', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('graph_draft_id', models.CharField(blank=True, max_length=512)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reply', to='core.inboundemail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='inbound/evidence/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.attachment')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.inboundemail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('transport', models.CharField(choices=[('IMAP', 'IMAP / SMTP'), ('GRAPH', 'Microsoft 365 / Graph')], default='IMAP', max_length=12)),
                ('is_active', models.BooleanField(default=False)),
                ('imap_host', models.CharField(blank=True, max_length=200)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=200)),
                ('credential_reference', models.CharField(blank=True, help_text='Environment variable holding the IMAP password or OAuth access token.', max_length=160)),
                ('use_oauth', models.BooleanField(default=False)),
                ('folder', models.CharField(default='INBOX', max_length=100)),
                ('graph_tenant_id', models.CharField(blank=True, max_length=120)),
                ('graph_client_id', models.CharField(blank=True, max_length=120)),
                ('graph_secret_reference', models.CharField(blank=True, max_length=160)),
                ('auto_submit', models.BooleanField(default=False, help_text='After successful validation, continue through the existing approval/STP workflow.')),
                ('require_sender_authentication', models.BooleanField(default=True, help_text='Require an aligned DMARC pass from a configured trusted Authentication-Results server before applying email data.')),
                ('trusted_authserv_ids', models.JSONField(blank=True, default=list, help_text='Exact authserv-id names of your receiving mail servers. Ignore Authentication-Results from any other server.')),
                ('cursor', models.JSONField(blank=True, default=dict, editable=False)),
                ('last_sync_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('default_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.mailboxconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'message_uid'), name='uq_mailbox_message_uid'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('mailbox', 'message_id'), name='uq_mailbox_message_id'),
        ),
    ]
