# Generated by Django 5.2.17 on 2026-10-06 10:38

import core.credentials
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_email_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxconfiguration',
            name='credential_reference',
            field=models.CharField(blank=True, help_text='Environment variable name, e.g. ENDORSEMENT_IMAP_PASSWORD. Set its value in .env or the worker environment. Do not enter the password/token here.', max_length=160, validators=[core.credentials.validate_credential_reference]),
        ),
        migrations.AlterField(
            model_name='mailboxconfiguration',
            name='graph_secret_reference',
            field=models.CharField(blank=True, help_text='Environment variable name, e.g. ENDORSEMENT_GRAPH_CLIENT_SECRET. Set its value to the Entra client secret VALUE in .env or the worker environment. Do not enter the secret or its ID here.', max_length=160, validators=[core.credentials.validate_credential_reference]),
        ),
    ]
