# Generated by Django 5.2.17 on 2026-10-06 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_admin_mailbox_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='reply_backend',
            field=models.CharField(choices=[('SMTP', 'SMTP delivery'), ('CONSOLE', 'Console (development only)')], default='SMTP', help_text='Used for IMAP replies. Graph mailboxes send native Microsoft 365 replies.', max_length=12),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_password',
            field=models.TextField(blank=True, help_text='Enter the SMTP password or app password directly here.'),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_timeout',
            field=models.PositiveIntegerField(default=30, help_text='SMTP connection timeout in seconds.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='SMTP implicit TLS / SSL'),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP STARTTLS'),
        ),
        migrations.AddField(
            model_name='mailboxconfiguration',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='Leave blank for an SMTP relay that does not require authentication.', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailboxconfiguration',
            name='graph_client_secret',
            field=models.TextField(blank=True, help_text='Enter the full client secret Value from Entra App registrations > Certificates & secrets.'),
        ),
        migrations.AlterField(
            model_name='mailboxconfiguration',
            name='imap_password',
            field=models.TextField(blank=True, help_text='Enter the mailbox password, app password or OAuth access token directly here.', verbose_name='IMAP password / OAuth token'),
        ),
    ]
